[package]
description = "一个Atomic-like的双索引<实体-属性>数据结构"
edition = "2021"
license = "MIT"
name = "retable"
version = "0.4.5"
type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { version = "0.12.1", features = ["serde"] }
rand = "0.8.5"
rustc-hash = "1.1.0"
serde = { version = "1.0.189", features = ["derive"] }
ron = "0.8"
num-traits = "0.2.17"
bincode = "1.3.3"
kv = "0.24.0"
# bimap = { version = "0.6.3", features = ["serde"] }
# multi_index_map = "0.9.0"
# sharded-slab = "0.1.1"

[dev-dependencies]
criterion = "0.5.1"

# [[bench]]
# name = "bench_props"
# harness = false
