[package]
description = "一个Atomic-like的双索引<实体-属性>数据结构"
edition = "2021"
license = "MIT"
name = "retable"
type = ["lib"]
version = "0.5.1-a"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
as-bytes = "0.2.0"
kv = { version = "0.24.0", features = ["bincode-value"] }
parking_lot = { version = "0.12.1", features = ["serde"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.189", features = ["derive"] }
sled = "0.34.7"
thiserror = "1.0.50"

[dev-dependencies]
criterion = "0.5.1"

# [[bench]]
# name = "bench_props"
# harness = false
