[package]
description = "一个Atomic-like的双索引<实体-属性>数据结构"
edition = "2021"
license = "MIT"
name = "retable"
version = "0.3.0-rc1"
type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multi_index_map = "0.9.0"
rand = "0.8.5"
# ron = "0.8.1"
serde = {version = "1.0.189", features = ["derive"]}
sharded-slab = "0.1.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench_props"
harness = false
