[package]
description = "An Atomic-like double indexed entity-attribute data structures."
authors = ["RuofengX <<i@ruofengx.cn>>"]
categories = ["database"]
keywords = ["database", "atomic", "double-indexed", "entity-attribute", "ecs"]
readme = "README.md"
edition = "2021"
license = "MIT"
name = "retable"
version = "0.7.0-alpha.3"
repository = "https://github.com/RuofengX/retable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12.1"
