[package]
description = "一个Atomic-like的双索引<实体-属性>数据结构"
edition = "2021"
license = "MIT"
name = "retable"
version = "0.6.0"
repository = "https://github.com/RuofengX/retable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moka = { version = "0.12.1", features = ["sync"] }
serde = { version = "1.0.189", features = ["derive"] }
sled = "0.34.7"
thiserror = "1.0.50"
typed-sled = "0.2.3"
