[package]
name = "retable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.7.0"
multi_index_map = "0.9.0"
redb = "1.2.0"
sled = "0.34.7"
