[package]
name = "mykv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc"
im = { version = "15.1.0", features = ["serde", "rayon"] }
parking_lot = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }
slab = "0.4.9"
zerocopy = { version = "0.7.31", features = ["alloc"] }
zerocopy-derive = "0.7.31"
