[package]
description = "An Atomic-like double indexed entity-attribute data structures."
authors = ["RuofengX <<i@ruofengx.cn>>"]
categories = ["database"]
keywords = ["database", "atomic", "double-indexed", "entity-attribute", "ecs"]
readme = "README"
edition = "2021"
license = "MIT"
name = "retable"
version = "0.6.1"
repository = "https://github.com/RuofengX/retable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moka = { version = "0.12.1", features = ["sync"] }
rayon = "1.8.0"
serde = { version = "1.0.189", features = ["derive"] }
sled = "0.34.7"
thiserror = "1.0.50"
typed-sled = "0.2.3"
